version: "3.9"
services:
  aplication:
    build: .
    ports:
      - "5000:5000"
    links:
      - database
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_INITDB_ROOT_USERNAME=admin
      - MYSQL_INIT_ROOT_PASSWORD=notPermiissionsNedded123
      - DB_HOST=database
      - APP_PORT=5000
